### ISSUE TITLE
cd crashes on .. in /

### ISSUE THREAD

**Issue by 2ECC71** [loxtank/INTE-project#103]

**Comment by 2ECC71** [comment]
om man gör cd .. i / foldern krashar programet med en nullpointer:

/Users $ cd ..
/ $ cd ..
Exception in thread "main" java.lang.NullPointerException
    at java.nio.file.Files.provider(Files.java:97)
    at java.nio.file.Files.exists(Files.java:2385)
    at org.pucko.commands.Cd.validate(Cd.java:72)
    at org.pucko.core.CommandRunner.runCommands(CommandRunner.java:17)
    at org.pucko.core.Controller.parseCommand(Controller.java:22)
    at org.pucko.core.Menu.run(Menu.java:22)
    at org.pucko.core.Program.main(Program.java:13)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Process finished with exit code 1
